#!/usr/bin/env node
/**
 * optimize-images.cjs
 * Converts profile.jpg → profile.webp (400×400) and profile@2x.webp (800×800)
 * Also creates a small LQIP placeholder (16×16 base64) for blur-up technique.
 * Run: node scripts/optimize-images.cjs
 */
const sharp = require('sharp');
const fs    = require('fs');
const path  = require('path');

const SRC   = path.join(__dirname, '..', 'public', 'profile.jpg');
const OUT   = path.join(__dirname, '..', 'public');

async function run() {
  if (!fs.existsSync(SRC)) {
    console.error('❌  public/profile.jpg not found');
    process.exit(1);
  }

  // 1× WebP  — 400 px, quality 82
  await sharp(SRC)
    .resize(400, 400, { fit: 'cover', position: 'top' })
    .webp({ quality: 82 })
    .toFile(path.join(OUT, 'profile.webp'));
  console.log('✅  profile.webp  (400×400)');

  // 2× WebP  — 800 px, quality 82
  await sharp(SRC)
    .resize(800, 800, { fit: 'cover', position: 'top' })
    .webp({ quality: 82 })
    .toFile(path.join(OUT, 'profile@2x.webp'));
  console.log('✅  profile@2x.webp  (800×800)');

  // LQIP (low-quality image placeholder) — 20px, blur 4
  const lqipBuf = await sharp(SRC)
    .resize(20, 20, { fit: 'cover', position: 'top' })
    .webp({ quality: 20 })
    .toBuffer();
  const lqipB64 = 'data:image/webp;base64,' + lqipBuf.toString('base64');

  // Write LQIP as a tiny JS module so React can import it
  const lqipOut = path.join(__dirname, '..', 'src', 'assets', 'profileLqip.ts');
  fs.mkdirSync(path.dirname(lqipOut), { recursive: true });
  fs.writeFileSync(lqipOut, `// Auto-generated by scripts/optimize-images.cjs\nexport const profileLqip = "${lqipB64}";\n`);
  console.log('✅  src/assets/profileLqip.ts  (LQIP base64)');

  const sizes = {
    original:  fs.statSync(SRC).size,
    webp1x:    fs.statSync(path.join(OUT, 'profile.webp')).size,
    webp2x:    fs.statSync(path.join(OUT, 'profile@2x.webp')).size,
  };
  console.log(`\n📦  Size savings:`);
  console.log(`   original  : ${(sizes.original  / 1024).toFixed(1)} KiB`);
  console.log(`   profile.webp  : ${(sizes.webp1x   / 1024).toFixed(1)} KiB  (${Math.round((1 - sizes.webp1x  / sizes.original) * 100)}% smaller)`);
  console.log(`   profile@2x.webp : ${(sizes.webp2x   / 1024).toFixed(1)} KiB  (${Math.round((1 - sizes.webp2x / sizes.original) * 100)}% smaller)`);
}

run().catch(err => { console.error(err); process.exit(1); });
